/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: indri.i

#ifndef SWIG_indri_go_WRAP_H_
#define SWIG_indri_go_WRAP_H_

class Swig_memory;

class SwigDirector_IndexStatus : public indri::api::IndexStatus
{
 public:
  SwigDirector_IndexStatus(int swig_p);
  virtual ~SwigDirector_IndexStatus();
  virtual void status(int code, std::string const &documentPath, std::string const &error, int documentsIndexed, int documentsSeen);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
